version: '3.9'

services:
  frontend:
    image: jananibalan/frontend:latest
    container_name: todo-frontend
    ports:
      - "80:80"
    networks:
      - connect-network
    depends_on:
      - backend

  backend:
    image: jananibalan/backend:latest
    container_name: todo-backend
    ports:
      - "5000:5000"
    networks:
      - connect-network
    environment:
      SECRET_NAME: "todo/db-creds"
      AWS_REGION: "ap-south-1"
    depends_on:
      database:
        condition: service_healthy


  database:
    image: mysql:8.0.45-debian
    container_name: todo-db
    networks:
      - connect-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
    - ~/schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  connect-network:
    driver: bridge