apiVersion: v1 
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-config
data: 
  DB_HOST: "{{ .Values.backend.env.DB_HOST }}"
  DB_PORT: "{{ .Values.backend.env.DB_PORT }}"
  DB_NAME: "{{ .Values.backend.env.DB_NAME }}"
