apiVersion: v1 
kind: PersistentVolumeClaim

metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes:
  - {{ .Values.mysql.persistent.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistent.size }}
