apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql

spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:   # 👈 VERY IMPORTANT (this was broken earlier)
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            - name: init-script
              mountPath: /docker-entrypoint-initdb.d

          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_DATABASE

      volumes:   # 👈 MUST be inside spec (NOT outside)
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc

        - name: init-script
          configMap:
            name: {{ .Release.Name }}-mysql-init